// Countries actions
export const GET_COUNTRIES_REQUESTING = 'GET_COUNTRIES_REQUESTING';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';

// Person actions
export const ADD_A_PERSON = 'ADD_A_PERSON';

export const SAVE_PERSONS_LS_REQUESTING = 'SAVE_PERSONS_LS_REQUESTING';
export const SAVE_PERSONS_LS_SUCCESS = 'SAVE_PERSONS_LS_SUCCESS';
export const SAVE_PERSONS_LS_ERROR = 'SAVE_PERSONS_LS_ERROR';

export const LOAD_PERSONS_LS_REQUESTING = 'LOAD_PERSONS_LS_REQUESTING';
export const LOAD_PERSONS_LS_SUCCESS = 'LOAD_PERSONS_LS_SUCCESS';
export const LOAD_PERSONS_LS_ERROR = 'LOAD_PERSONS_LS_ERROR';

// Notification derivate data
export const GET_DERIVATE_DATA = 'GET_DERIVATE_DATA';
export const DISABLE_NOTIFICATION = 'DISABLE_NOTIFICATION';
